### ISSUE TITLE
setup.py:energy_minimize ignores mdp parameter

### ISSUE THREAD

**Issue by luancarvalhomartins** [Becksteinlab/GromacsWrapper#123]
In setup.py, line 662:

`mdp = deffnm+'.mdp'`

This overwrites user-supplied mdp parameter.

**Comment by orbeckst** [comment]
[Yes](https://github.com/Becksteinlab/GromacsWrapper/blob/develop/gromacs/setup.py#L662) – if you want to provide a PR I am happy to merge it. I won't be able to work on it during this week.

**Comment by luancarvalhomartins** [comment]
I can do so, but only Friday to Sunday. Would you rather prefer `setup.py:energy_minimize` to try to alter user-supplied mdp file through `cbook.py:editmdp` or to use it as is? I tend to think that the former allows more flexibility.

You are welcome.

**Comment by orbeckst** [comment]
I would 'use as is'. 

Whenever you submit a PR is fine. It's open source, you contribute when you can. (And you will be listed as an author of GW). 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by orbeckst** [comment]
I understood this issue that a user-supplied `mdp` parameter in function `gromacs.setup.energy_minimize(mdp="custom.mdp") is ignored. In fact, this is *not* true and it works just fine with a supplied mdp file. The code is not very clear because the variable `mdp` changes meaning half-way through (sorry). I added a comment to the code and a test for a custom mdp file in PR #128.

(It is true that a custom `em/em.mdp` file would be *overwritten* and this is not checked for.)
