### ISSUE TITLE
How do you make this work with gromacs 5.1.x?

### ISSUE THREAD

**Issue by dotsdl** [Becksteinlab/GromacsWrapper#26]
With gromacs 5.1 comes the disappearance of the use of gromacs tools on their own. For example,  `trjconv` now must be called with `gmx trjconv`. What changes need to happen to the library to make this work?

**Comment by orbeckst** [comment]
It's a bit cumbersome but you "just" have to edit your configuration file.I just pushed out 0.4.0 and that should also update the docs.

In the tools section, describe `gmx trjconv` as
```
   gmx:trjconv
```
There are a few hard-coded hacks in there that alias new to old names (such as genbox). See 9208d52d2323b57866b2a600659cb75b400b03ff .

**Comment by orbeckst** [comment]
See http://gromacswrapper.readthedocs.org/en/develop/gromacs/core/config.html#gromacs-tools-and-scripts ; took me a while to get RTD to build again. (master/latest should also be available again soon)

**Comment by dotsdl** [comment]
Okay, I edited my `~/.gromacswrapper.cfg` file to include only names in the current release (5.1.1) of gromacs with the `gmx:` prefix, removing old ones. That was a bit of work...

Looks like there might be few hard-codes left in the codebase; there's at least one [here in the cookbook](https://github.com/Becksteinlab/GromacsWrapper/blob/develop/gromacs/cbook.py#L166).

Should we make this issue the focal point for making the library work from the start with gromacs 5.x only beginning with the next release? I don't think much more needs to be done (famous last words) besides finding any more hardcodes and setting the defaults in `gromacswrapper.cfg` to use the correct names.

**Comment by orbeckst** [comment]
Instead of cleaning up the "hard codes" I'd actually favor a compatibility layer that allows you to either use 4.x or 5.x. That would be useful, at least for the next year or so where we are almost certainly still using 4.x from old projects and 5.x for new ones.  The [current hack in gromacs.tools](https://github.com/Becksteinlab/GromacsWrapper/blob/develop/gromacs/tools.py#L198) is not pretty at the moment but it is possible, at least for commands that only changed name. One could, of course, make a translation table and use this in a more data-driven way.

The canned command in the cook-book are a bit of a headache if the underlying G-command ceased to exist.

Overall, I agree with you that for 0.5 we should ship with 5.x defaults. A mechanism to switch between versions in the cfg file would be nice.

**Comment by whitead** [comment]
Do you think it would be possible to improve the configuration a little bit to detect available tools and release version? For example, I could generate templates for a few different gromacs versions and then use `gmx info` or the first line of `grompp` to detect the version. I can write this if this sounds feasible/useful.

**Comment by orbeckst** [comment]
That would be awesome!

--
Oliver Beckstein
email: orbeckst@gmail.com


Am Apr 6, 2016 um 9:10 schrieb Andrew White <notifications@github.com>:

**Comment by orbeckst** [comment]
PR #53 switched the default over to 5.x configuration so I am closing this issue.

Further work (#49 etc) needs to address how to make this work with old 4.x installations.

**Comment by orbeckst** [comment]
I opened #54 for working with Gromacs 4.x.
