### ISSUE TITLE
Python 3.12: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by njzjz** [Becksteinlab/GromacsWrapper#263]
```
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/gromacs/__init__.py", line 218, in <module>
    from . import config
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/gromacs/config.py", line 266, in <module>
    from pkg_resources import resource_filename, resource_listdir
ModuleNotFoundError: No module named 'pkg_resources'
```

`pkg_resources` is a part of `setuptools`, and https://github.com/python/cpython/issues/95299 removes `setuptools` from Python environments. It needs to be manually added to the requirements.

**Comment by orbeckst** [comment]
Probably better to replace it with `importlib` anyway.

**Comment by orbeckst** [comment]
p.s.: PRs welcome :-)

**Comment by jandom** [comment]
'importlib' is not my forte, so i'm not going to venture into this, unless with a help from ChatGPT... For now can we get started with declaring the dependency on `setuptools`? That's easy enough to add. 

I've had issues reproducing the bug because setuptools are installed (somehow) when creating a developer env using the `test_env.yaml`

**Comment by orbeckst** [comment]
Band-aid is good enough — if you have a fix, please do a PR!

In MDAnalysisData we recently did the replacement https://github.com/MDAnalysis/MDAnalysisData/pull/76 

path = importlib.resources.files('MDAnalysisData') / description_dir / filename

**Comment by jandom** [comment]
Okay, here is my proposed band-aid https://github.com/Becksteinlab/GromacsWrapper/pull/271/
